# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    subscriptionId: 'a8108c2b-496c-424d-8347-ecc8afb6384c'
    location: 'switzerlandnorth'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/dor054/ms-home-assignment-dev/blob/main/template_storage_try1/template.json'
    csmParametersFileLink: 'https://github.com/dor054/ms-home-assignment-dev/blob/main/template_storage_try1/parameters.json'
    deploymentMode: 'Incremental'

- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
